export const CAMEROON_COLORS = {
  GREEN: '#007A5E',
  RED: '#CE1126',
  YELLOW: '#FCD116',
};

export const LANGUAGES: Record<string, { name: string; flag: string }> = {
  en: { name: 'English', flag: '🇬🇧' },
  fr: { name: 'Français', flag: '🇫🇷' },
  es: { name: 'Español', flag: '🇪🇸' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  it: { name: 'Italiano', flag: '🇮🇹' },
  pt: { name: 'Português', flag: '🇵🇹' },
  ru: { name: 'Русский', flag: '🇷🇺' },
  ja: { name: '日本語', flag: '🇯🇵' },
  zh: { name: '中文', flag: '🇨🇳' },
  ko: { name: '한국어', flag: '🇰🇷' },
  ar: { name: 'العربية', flag: '🇸🇦' },
  hi: { name: 'हिंदी', flag: '🇮🇳' },
  pl: { name: 'Polski', flag: '🇵🇱' },
  tr: { name: 'Türkçe', flag: '🇹🇷' },
  nl: { name: 'Nederlands', flag: '🇳🇱' },
  sv: { name: 'Svenska', flag: '🇸🇪' },
  no: { name: 'Norsk', flag: '🇳🇴' },
  da: { name: 'Dansk', flag: '🇩🇰' },
  fi: { name: 'Suomi', flag: '🇫🇮' },
  el: { name: 'Ελληνικά', flag: '🇬🇷' },
  cs: { name: 'Čeština', flag: '🇨🇿' },
  hu: { name: 'Magyar', flag: '🇭🇺' },
  ro: { name: 'Română', flag: '🇷🇴' },
  uk: { name: 'Українська', flag: '🇺🇦' },
  th: { name: 'ไทย', flag: '🇹🇭' },
  vi: { name: 'Tiếng Việt', flag: '🇻🇳' },
  id: { name: 'Bahasa Indonesia', flag: '🇮🇩' },
  ms: { name: 'Bahasa Melayu', flag: '🇲🇾' },
  tl: { name: 'Tagalog', flag: '🇵🇭' },
  bn: { name: 'বাংলা', flag: '🇧🇩' },
  pa: { name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  ml: { name: 'മലയാളം', flag: '🇮🇳' },
  ta: { name: 'தமிழ்', flag: '🇮🇳' },
  te: { name: 'తెలుగు', flag: '🇮🇳' },
  kn: { name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  mr: { name: 'मराठी', flag: '🇮🇳' },
  fa: { name: 'فارسی', flag: '🇮🇷' },
  he: { name: 'עברית', flag: '🇮🇱' },
  ur: { name: 'اردو', flag: '🇵🇰' },
  sw: { name: 'Swahili', flag: '🇹🇿' },
  af: { name: 'Afrikaans', flag: '🇿🇦' },
  am: { name: 'አማርኛ', flag: '🇪🇹' },
  ca: { name: 'Català', flag: '🇪🇸' },
  eu: { name: 'Euskera', flag: '🇪🇸' },
  gl: { name: 'Galego', flag: '🇪🇸' },
  hy: { name: 'Հայերեն', flag: '🇦🇲' },
  ka: { name: 'ქართული', flag: '🇬🇪' },
  bg: { name: 'Български', flag: '🇧🇬' },
  hr: { name: 'Hrvatski', flag: '🇭🇷' },
  sk: { name: 'Slovenčina', flag: '🇸🇰' },
  sl: { name: 'Slovenščina', flag: '🇸🇮' },
  lt: { name: 'Lietuvių', flag: '🇱🇹' },
  lv: { name: 'Latviešu', flag: '🇱🇻' },
  et: { name: 'Eesti', flag: '🇪🇪' },
};

export const DEFAULT_LANGUAGE = 'en';

export const STORAGE_KEYS = {
  LANGUAGE: 'nky_language',
  USER: 'nky_user',
} as const;

export const VALIDATION = {
  MIN_PASSWORD_LENGTH: 8,
  MIN_FULL_NAME_LENGTH: 2,
} as const;
